#!/bin/sh
# $Id: build-openafs,v 1.1 2002/01/14 07:49:17 shadow Exp $
FS=${FS:-${objdir}/../appl/fs/fs}

${FS} sq . 0
wget http://www.openafs.org/dl/1.2.2/openafs-1.2.2-src.tar.gz >& 4
if test "X$FAST" != "X" ; then echo "Not running $0" ;  exit 0 ; fi
$SHELL $SHELLVERBOSE $srcdir/generic-build openafs-1.2.2-src.tar.gz openafs-1.2.2
openafs-1.2.2/src/finale/translate_et 180480 >& /dev/null
